// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	crdv1alpha1 "antrea.io/theia/pkg/client/clientset/versioned/typed/crd/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeThroughputAnomalyDetectors implements ThroughputAnomalyDetectorInterface
type fakeThroughputAnomalyDetectors struct {
	*gentype.FakeClientWithList[*v1alpha1.ThroughputAnomalyDetector, *v1alpha1.ThroughputAnomalyDetectorList]
	Fake *FakeCrdV1alpha1
}

func newFakeThroughputAnomalyDetectors(fake *FakeCrdV1alpha1, namespace string) crdv1alpha1.ThroughputAnomalyDetectorInterface {
	return &fakeThroughputAnomalyDetectors{
		gentype.NewFakeClientWithList[*v1alpha1.ThroughputAnomalyDetector, *v1alpha1.ThroughputAnomalyDetectorList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("throughputanomalydetectors"),
			v1alpha1.SchemeGroupVersion.WithKind("ThroughputAnomalyDetector"),
			func() *v1alpha1.ThroughputAnomalyDetector { return &v1alpha1.ThroughputAnomalyDetector{} },
			func() *v1alpha1.ThroughputAnomalyDetectorList { return &v1alpha1.ThroughputAnomalyDetectorList{} },
			func(dst, src *v1alpha1.ThroughputAnomalyDetectorList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ThroughputAnomalyDetectorList) []*v1alpha1.ThroughputAnomalyDetector {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ThroughputAnomalyDetectorList, items []*v1alpha1.ThroughputAnomalyDetector) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
