// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	crdv1alpha1 "antrea.io/theia/pkg/client/clientset/versioned/typed/crd/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetworkPolicyRecommendations implements NetworkPolicyRecommendationInterface
type fakeNetworkPolicyRecommendations struct {
	*gentype.FakeClientWithList[*v1alpha1.NetworkPolicyRecommendation, *v1alpha1.NetworkPolicyRecommendationList]
	Fake *FakeCrdV1alpha1
}

func newFakeNetworkPolicyRecommendations(fake *FakeCrdV1alpha1, namespace string) crdv1alpha1.NetworkPolicyRecommendationInterface {
	return &fakeNetworkPolicyRecommendations{
		gentype.NewFakeClientWithList[*v1alpha1.NetworkPolicyRecommendation, *v1alpha1.NetworkPolicyRecommendationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("networkpolicyrecommendations"),
			v1alpha1.SchemeGroupVersion.WithKind("NetworkPolicyRecommendation"),
			func() *v1alpha1.NetworkPolicyRecommendation { return &v1alpha1.NetworkPolicyRecommendation{} },
			func() *v1alpha1.NetworkPolicyRecommendationList { return &v1alpha1.NetworkPolicyRecommendationList{} },
			func(dst, src *v1alpha1.NetworkPolicyRecommendationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NetworkPolicyRecommendationList) []*v1alpha1.NetworkPolicyRecommendation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.NetworkPolicyRecommendationList, items []*v1alpha1.NetworkPolicyRecommendation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
