apiVersion: v1
entries:
  theia:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "false"
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.9.0
    created: "2026-07-01T16:56:17.635394118-05:00"
    description: Antrea Network Flow Visibility
    digest: 1606be4be222db3e47a1627a0e487c232128f5a594f3eeded5ee1ff3b031fb3f
    home: https://antrea.io/
    icon: https://raw.githubusercontent.com/antrea-io/antrea/main/docs/assets/logo/antrea_logo.svg
    keywords:
    - Kubernetes
    - CNCF
    - Networking
    - CNI
    - Security
    - Open vSwitch
    - OVS
    - Antrea
    - Observability
    - Flow visibility
    kubeVersion: '>= 1.16.0-0'
    name: theia
    sources:
    - https://github.com/antrea-io/theia
    type: application
    urls:
    - https://raw.githubusercontent.com/Scoobed/theia/main/charts/theia-0.9.0.tgz
    version: 0.9.0
generated: "2026-07-01T16:56:17.625361662-05:00"
