// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	crdv1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkPolicyRecommendationLister helps list NetworkPolicyRecommendations.
// All objects returned here must be treated as read-only.
type NetworkPolicyRecommendationLister interface {
	// List lists all NetworkPolicyRecommendations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crdv1alpha1.NetworkPolicyRecommendation, err error)
	// NetworkPolicyRecommendations returns an object that can list and get NetworkPolicyRecommendations.
	NetworkPolicyRecommendations(namespace string) NetworkPolicyRecommendationNamespaceLister
	NetworkPolicyRecommendationListerExpansion
}

// networkPolicyRecommendationLister implements the NetworkPolicyRecommendationLister interface.
type networkPolicyRecommendationLister struct {
	listers.ResourceIndexer[*crdv1alpha1.NetworkPolicyRecommendation]
}

// NewNetworkPolicyRecommendationLister returns a new NetworkPolicyRecommendationLister.
func NewNetworkPolicyRecommendationLister(indexer cache.Indexer) NetworkPolicyRecommendationLister {
	return &networkPolicyRecommendationLister{listers.New[*crdv1alpha1.NetworkPolicyRecommendation](indexer, crdv1alpha1.Resource("networkpolicyrecommendation"))}
}

// NetworkPolicyRecommendations returns an object that can list and get NetworkPolicyRecommendations.
func (s *networkPolicyRecommendationLister) NetworkPolicyRecommendations(namespace string) NetworkPolicyRecommendationNamespaceLister {
	return networkPolicyRecommendationNamespaceLister{listers.NewNamespaced[*crdv1alpha1.NetworkPolicyRecommendation](s.ResourceIndexer, namespace)}
}

// NetworkPolicyRecommendationNamespaceLister helps list and get NetworkPolicyRecommendations.
// All objects returned here must be treated as read-only.
type NetworkPolicyRecommendationNamespaceLister interface {
	// List lists all NetworkPolicyRecommendations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crdv1alpha1.NetworkPolicyRecommendation, err error)
	// Get retrieves the NetworkPolicyRecommendation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*crdv1alpha1.NetworkPolicyRecommendation, error)
	NetworkPolicyRecommendationNamespaceListerExpansion
}

// networkPolicyRecommendationNamespaceLister implements the NetworkPolicyRecommendationNamespaceLister
// interface.
type networkPolicyRecommendationNamespaceLister struct {
	listers.ResourceIndexer[*crdv1alpha1.NetworkPolicyRecommendation]
}
