// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	crdv1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ThroughputAnomalyDetectorLister helps list ThroughputAnomalyDetectors.
// All objects returned here must be treated as read-only.
type ThroughputAnomalyDetectorLister interface {
	// List lists all ThroughputAnomalyDetectors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crdv1alpha1.ThroughputAnomalyDetector, err error)
	// ThroughputAnomalyDetectors returns an object that can list and get ThroughputAnomalyDetectors.
	ThroughputAnomalyDetectors(namespace string) ThroughputAnomalyDetectorNamespaceLister
	ThroughputAnomalyDetectorListerExpansion
}

// throughputAnomalyDetectorLister implements the ThroughputAnomalyDetectorLister interface.
type throughputAnomalyDetectorLister struct {
	listers.ResourceIndexer[*crdv1alpha1.ThroughputAnomalyDetector]
}

// NewThroughputAnomalyDetectorLister returns a new ThroughputAnomalyDetectorLister.
func NewThroughputAnomalyDetectorLister(indexer cache.Indexer) ThroughputAnomalyDetectorLister {
	return &throughputAnomalyDetectorLister{listers.New[*crdv1alpha1.ThroughputAnomalyDetector](indexer, crdv1alpha1.Resource("throughputanomalydetector"))}
}

// ThroughputAnomalyDetectors returns an object that can list and get ThroughputAnomalyDetectors.
func (s *throughputAnomalyDetectorLister) ThroughputAnomalyDetectors(namespace string) ThroughputAnomalyDetectorNamespaceLister {
	return throughputAnomalyDetectorNamespaceLister{listers.NewNamespaced[*crdv1alpha1.ThroughputAnomalyDetector](s.ResourceIndexer, namespace)}
}

// ThroughputAnomalyDetectorNamespaceLister helps list and get ThroughputAnomalyDetectors.
// All objects returned here must be treated as read-only.
type ThroughputAnomalyDetectorNamespaceLister interface {
	// List lists all ThroughputAnomalyDetectors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crdv1alpha1.ThroughputAnomalyDetector, err error)
	// Get retrieves the ThroughputAnomalyDetector from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*crdv1alpha1.ThroughputAnomalyDetector, error)
	ThroughputAnomalyDetectorNamespaceListerExpansion
}

// throughputAnomalyDetectorNamespaceLister implements the ThroughputAnomalyDetectorNamespaceLister
// interface.
type throughputAnomalyDetectorNamespaceLister struct {
	listers.ResourceIndexer[*crdv1alpha1.ThroughputAnomalyDetector]
}
